QKQStore/Models/Products.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QKQStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int Id { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public int Price { get; set; }
        public Nullable<int> TotalPay { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}

QKQStore/Controllers/ProductsController.cs
using QKQStore.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QKQStore.Controllers
{
    public class ProductsController : Controller
    {
        QKQStoreEntities database = new QKQStoreEntities();
        // GET: Products
        public ActionResult Index()
        {
            return View(database.Products.Include("Categories").ToList());
        }
        //Hiển Thị Sản Phẩm Theo Danh Mục 
        public ActionResult TimDanhMuc(int categoryId)
        {
            var products = database.Products.Where(p => p.CategoryID == categoryId).ToList();
            return View("TimDanhMuc", products);
        }
        [HttpGet]
        public ActionResult Create() { return View(); }
        [HttpPost]
        public ActionResult Create(Products products, HttpPostedFileBase imageUpload)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    if(imageUpload != null)
                    {
                        string fileName = Path.GetFileName(imageUpload.FileName);
                        string path = Path.Combine(Server.MapPath("~/Content/Pic/"), fileName);
                        imageUpload.SaveAs(path);
                        products.Image = fileName;
                    }
                    products.Title = products.Title?.Trim();
                    products.CreateAt = DateTime.Now;
                    database.Products.Add(products);
                    database.SaveChanges();
                }
                return RedirectToAction("SanPham","Admin");
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            var porduct = database.Products.Find(id);
            return View(porduct);
        }
        public ActionResult DetailsAdmin(int id)
        {
            var porduct = database.Products.Find(id);
            return View(porduct);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var product = database.Products.Find(id);
            return View(product);
        }
        [HttpPost]
        public ActionResult Edit(Products products, HttpPostedFileBase imageUpload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var proDB = database.Products.Find(products.Id);
                    proDB.Title = products.Title;
                    proDB.Description = products.Description;
                    proDB.Price = products.Price;
                    proDB.Discount = products.Discount;
                    proDB.CategoryID = products.CategoryID;

                    if (imageUpload != null)
                    {
                        string fileName = Path.GetFileName(imageUpload.FileName);
                        string path = Path.Combine(Server.MapPath("~/Content/Pic/"), fileName);
                        imageUpload.SaveAs(path);
                        proDB.Image = fileName;
                    }
                    

                    proDB.UpdateAt = DateTime.Now;
                    database.SaveChanges();
                }
                return RedirectToAction("SanPham", "Admin");
            }
            catch (Exception ex)
            {
                return View(products);
            }
        }

       
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var porduct = database.Products.Find(id);
            return View(porduct);
        }
        [HttpPost]
        public ActionResult Delete(Products products,int id)
        {
            try
            {
                products= database.Products.Find(id);
                database.Products.Remove(products);
                products.UpdateAt = DateTime.Now;
                database.SaveChanges();
                return RedirectToAction("SanPham", "Admin");
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        
        //Chức năng tìm kiếm
        public ActionResult Search(string query)
        {
            var result = database.Products.Where(p => p.Title.Contains(query)).ToList();
            ViewBag.Query = query;
            return View("Kqtimkiem", result);
        }
        public ActionResult Kqtimkiem()
        {
            return View();
        }
    }

}

    

QKQStore/Views/Products/Create.cshtml
@model QKQStore.Models.Products

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Tạo Mới Sản Phẩm";
}

@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thêm Mới Sản Phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryID, "Vui Lòng Điền Đầy Đủ Thông Tin", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "Vui Lòng Điền Đầy Đủ Thông Tin ", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "Vui Lòng Điền Đầy Đủ Thông Tin", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discount, "Vui Lòng Điền Đầy Đủ Thông Tin", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="imageUpload" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "Vui Lòng Điền Đầy Đủ Thông Tin", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo Mới" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Lại", "SanPham","Admin")
</div>

QKQStore/Views/Products/Delete.cshtml
@model QKQStore.Models.Products
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
   
}
<h3>Bạn Có Muốn Xóa Sản Phẩm?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdateAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdateAt)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <a href="@Url.Action("IndexAdmin","Admin")">    <input type="submit" value="Xóa" class="btn btn-success" /> |</a>
          @Html.ActionLink("Trở Lại", "SanPham","Admin")
        </div>
    }
</div>

QKQStore/Views/Products/Details.cshtml
@using QKQStore.Models@model  QKQStore.Models.Products@{    ViewBag.Title = "Details";    Layout = "~/Views/Shared/_Layout.cshtml";} <h2 class="mt-4">THÔNG TIN CHI TIẾT SẢN PHẨM</h2><br /><div class="row">    <div class="offset-md-1 col-md-4">        <img src="@Url.Content("~/Content/Pic/" + Model.Image)" alt="Ảnh sản phẩm" width="300" height="300" />    </div>    <div class="col-md-6 details">        <h3>Tên sản phẩm: @Model.Title</h3>        <p style="text-align: justify;">            <strong>Mô tả:</strong> @Model.Description        </p>        <p class="price">            Giá gốc:            <span style="text-decoration: line-through; color: gray; font-size: 20px;">                @String.Format("{0:0,0}", Model.Price) VNĐ            </span>        </p>        <p class="price">            Giá khuyến mãi:            <span style="color:red; font-size:32px; font-weight:bold;">                @String.Format("{0:0,0}", Model.Discount) VNĐ            </span>        </p>        <a class="btn btn-primary btn-lg" href="@Url.Action("Themsanpham", "GioHang", new { id = Model.Id })">            <i class="bi bi-cart-plus"></i> Thêm vào giỏ hàng        </a>    </div></div>

QKQStore/Views/Products/DetailsAdmin.cshtml
@using QKQStore.Models@model  QKQStore.Models.Products@{    ViewBag.Title = "Details";    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";}<h2 class="mt-4">THÔNG TIN CHI TIẾT SẢN PHẨM</h2><br /><div class="row">    <div class="offset-md-1 col-md-4">        <img src="@Url.Content("~/Content/Pic/" + Model.Image)" alt="Ảnh sản phẩm" width="300" height="300" />    </div>    <div class="col-md-6 details">        <h3>Tên sản phẩm: @Model.Title</h3>        <p style="text-align: justify;">            <strong>Mô tả:</strong> @Model.Description        </p>        <p class="price">            Giá gốc:            <span style="text-decoration: line-through; color: gray; font-size: 20px;">                @String.Format("{0:0,0}", Model.Price) VNĐ            </span>        </p>        <p class="price">            Giá khuyến mãi:            <span style="color:red; font-size:32px; font-weight:bold;">                @String.Format("{0:0,0}", Model.Discount) VNĐ            </span>        </p>           </div></div>

QKQStore/Views/Products/Edit.cshtml
@model QKQStore.Models.Products
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Chỉnh Sửa Sản Phẩm";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>

@using (Html.BeginForm("Edit", "Products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="imageUpload" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở Lại", "SanPham","Admin")
</div>

QKQStore/Views/Products/Index.cshtml
@model IEnumerable<QKQStore.Models.Products>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Quản Lý Sản Phẩm";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Tạo Mới", "Create")
</p>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Categories.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Title)</th>
        <th>@Html.DisplayNameFor(model => model.Price)</th>
        <th>@Html.DisplayNameFor(model => model.Discount)</th>
        <th>@Html.DisplayNameFor(model => model.Image)</th>
        <th>@Html.DisplayNameFor(model => model.Description)</th>
        <th>@Html.DisplayNameFor(model => model.CreateAt)</th>
        <th>@Html.DisplayNameFor(model => model.UpdateAt)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => item.Id)</td>
            <td>@Html.DisplayFor(m => item.Categories.Name)</td>
            <td>@Html.DisplayFor(m => item.Title)</td>
            <td>@Html.DisplayFor(m => item.Price)</td>
            <td>@Html.DisplayFor(m => item.Discount)</td>
            <td>
                <img src="@Url.Content("~/Content/Pic/" + item.Image)"alt="Ảnh sản phẩm" width="100" height="100" />
            </td>
            <td>@Html.DisplayFor(m => item.Description)</td>
            <td>@(item.CreateAt?.ToString("dd/MM/yyyy"))</td>
            <td>@(item.UpdateAt?.ToString("dd/MM/yyyy"))</td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Chi Tiết", "Details", new { id = item.Id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

QKQStore/Views/Products/Kqtimkiem.cshtml
@model List<QKQStore.Models.Products>
@{
    ViewBag.Title = "Kết quả tìm kiếm";
}

<h2>Kết quả cho: "@ViewBag.Query"</h2>

@if (Model.Count == 0)
{
    <p>Không tìm thấy sản phẩm nào.</p>
}
else
{
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 mb-4">
                <div class="card h-100">
                    <img src="@Url.Content("~/Content/Pic/" + item.Image)" style="width:150px;height:auto; margin-left:auto;margin-right:auto" alt="@item.Title" />
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <p class="card-text">@item.Price.ToString("N0") VNĐ</p>
                        <a href="/Products/Details/@item.Id" class="btn btn-primary">Xem chi tiết</a>
                    </div>
                </div>
            </div>
        }
    </div>
}

QKQStore/Views/Products/TimDanhMuc.cshtml
@model IEnumerable<QKQStore.Models.Products>
@{
    ViewBag.Title = "Sản phẩm theo danh mục";
    Layout = "~/Views/Shared/_Layout.cshtml"; // layout khách hàng
}

<h2 class="text-center my-4">Danh sách sản phẩm</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3 mb-4">
            <div class="card h-100 text-center">
                <img src="@Url.Content("~/Content/Pic/" + item.Image)" class="card-img-top" style="max-height:200px;" />
                <div class="card-body">
                    <h6>@item.Title</h6>
                    <p class="text-danger fw-bold">@item.Price.ToString("N0") VNĐ</p>
                    <a href="@Url.Action("Details","Products", new { id = item.Id })" class="btn btn-dark btn-sm">Xem chi tiết</a>
                </div>
            </div>
        </div>
    }
</div>